exclude = [
  # These websites return 403 forbidden codes for GitHub runners.
  '^https://www\.digikey\.com',
  '^https://www\.raspberrypi\.com',
]

cache = true
exclude_path = [".direnv/", "result/"]
max_cache_age = "2w"
