# accept = [429]

exclude = [
  # Raspberry Pi's website returns 403 forbidden codes for GitHub runners.
  '^https://www.raspberrypi.com',
]

cache = true
exclude_path = [".direnv/", "result/"]
max_cache_age = "2w"
