name: Build
"on":
  pull_request:
    paths:
      - "**.nix"
      - .github/workflows/build.yaml
      - flake.lock
  push:
    branches:
      - main
    paths:
      - "**.nix"
      - .github/workflows/build.yaml
      - flake.lock
  schedule:
    # Run at 04:10 on Sunday
    - cron: "10 4 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@v15
      # with:
      #   extra-conf: |
      #     extra-platforms = aarch64-linux
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Build the image
        run: nix build '.#piceiver-sd-image'
      - uses: actions/upload-artifact@v4
        with:
          name: piceiver-sd-image
          path: result/sd-image/nixos-sd-image-*-aarch64-linux.img.zst
